apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: library-ns
type: Opaque
data:
  mysql-root-password: cm9vdA== # "root" w Base64
  mysql-user: cm9vdA== # "root" w Base64
  mysql-password: cm9vdA== # "root" w Base64
